apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: spring-boot-starter-kit
build:
  artifacts:
  - image: 192.168.0.10:5000/spring-boot-starter-kit
    #jib: {}
    context: .
    docker:
      dockerfile: docker/Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes/deploy.yml
