##TEST RESOURCES###

##Oauth2Client Autoconfigure
security:
  oauth2:
    client:
      clientId: test_client
      clientSecret: test_secret
      #accessTokenUri: https://gravitee-am/domaine1/oauth/token
      #userAuthorizationUri: https://gravitee-am/domaine1/oauth/authorize
      #tokenName: access_token
      #grant-type: client_credentials
      #scope: openid
    resource:
      #userInfoUri: https://gravitee-am/domaine1/oidc/userinfo
      tokenInfoUri: https://gravitee-am/domaine1/oauth/introspect

#Access Management Admin
am:
  management:
    baseUri: http://localhost:8093/
    adminLogin: admin
    adminPassword: admin_int


logging:
  level:
    #org.springframework.web: debug
    #org.springframework.security: debug
    #org.springframework.web-security: debug
    org.springframework: error

spring:
    application:
      name: spring-boot-starter-kit
    #RabbitMQ properties
    rabbitmq:
      #addresses: fra-vsr-29378,fra-vsr-29379
      host: localhost
      port: 5672
      username: guest
      password: guest
      virtualHost: /
      listener:
        simple:
          prefetch: 5
          default-requeue-rejected: true
          retry:
            enabled: false
            initial-interval: 2000
            max-attempts: 2
            multiplier: 1.5
            max-interval: 500

    #MongoDB properties
    data.mongodb:
      #uri: mongodb://user:password@host1:27017/starterkit?authSource=starterkit&ssl=false
      uri: mongodb://guest:guest@localhost:27017/starterkit

    data.elasticsearch:
      urls:
        - http://localhost:9200
        #- http://localhost:9201
      connecttimeout: 5000
      sockettimeout: 60000
      index: account
      username: username
      password: password

logging.config: src/main/resources/logback.xml