##TEST RESOURCES###

##Oauth2Client Autoconfigure
security:
  oauth2:
    client:
      clientId: test_client
      clientSecret: test_secret
      #accessTokenUri: https://gravitee-am/domaine1/oauth/token
      #userAuthorizationUri: https://gravitee-am/domaine1/oauth/authorize
      #tokenName: access_token
      #grant-type: client_credentials
      #scope: openid
    resource:
      #userInfoUri: https://gravitee-am/domaine1/oidc/userinfo
      tokenInfoUri: https://gravitee-am/domaine1/oauth/introspect

#Access Management Admin
am:
  baseUri: http://gravitee-am:8092/

mongo:
  host: localhost
  port: 27017
  databaseName: amadmin


logging:
  level:
    #org.springframework.web: debug
    #org.springframework.security: debug
    #org.springframework.web-security: debug
    org.springframework: error

spring:
    application:
      name: amadmin
    #RabbitMQ properties
    rabbitmq.host: localhost
    rabbitmq.port: 5672
    rabbitmq.username: guest
    rabbitmq.password: guest
