apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWekNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFU0T1RBek9UWTJOREFlRncweU1EQTFNRGt4TlRVME1qUmFGdzB6TURBMU1EY3hOVFUwTWpSYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFU0T1RBek9UWTJOREJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkVJSDRjODYrS2Zrc2d6VlRoWlRRbnZ2Yk1EWkZtcTBnUW11d3NIZkgycWMKSEQzMzFrWHQ3MzdGR0RqN2syTXNUME5XQmdEeVF2UE1hUXA5blR2YVFxbWpJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUMwT3RCZVZDNElQCjFqTUswaEdHR2RheWdWR0c0YlcwbGo2MkQwM3RaTXQyQWlFQXVSQjZORXFsTmtOTnJkZFIvN1RQcVJmcVhXYS8Kb3FyOGg3RHhOMURzczlvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://10.112.40.223:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 49e015d2d74ec149047125056d262068
    username: admin
